// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5Kg6XV4208yu6kyyOsX0YEjfcSuNtDUE',
    appId: '1:484216259466:web:82e6a344aa0f5fbcd1fe73',
    messagingSenderId: '484216259466',
    projectId: 't-vac-c9ba2',
    authDomain: 't-vac-c9ba2.firebaseapp.com',
    storageBucket: 't-vac-c9ba2.appspot.com',
    measurementId: 'G-B6TBBDXPDV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE41LgGFlsEyniglDwFCI2AUgqJF14ZGI',
    appId: '1:484216259466:android:45594fac1e53af8bd1fe73',
    messagingSenderId: '484216259466',
    projectId: 't-vac-c9ba2',
    storageBucket: 't-vac-c9ba2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQITvmkRZhPH3dMHVcaJlvv9o9vjt5IDU',
    appId: '1:484216259466:ios:534ecbc18bb459f4d1fe73',
    messagingSenderId: '484216259466',
    projectId: 't-vac-c9ba2',
    storageBucket: 't-vac-c9ba2.appspot.com',
    iosBundleId: 'com.example.tVac',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQITvmkRZhPH3dMHVcaJlvv9o9vjt5IDU',
    appId: '1:484216259466:ios:9745bb3ecde9e268d1fe73',
    messagingSenderId: '484216259466',
    projectId: 't-vac-c9ba2',
    storageBucket: 't-vac-c9ba2.appspot.com',
    iosBundleId: 'com.example.tVac.RunnerTests',
  );
}
